- .github/workflows/deploy.yml
- .gitignore
CICD 파이프라인 구축하기 
- deploy.yml 파일 생성
---
전에 dev 에서 브랜치를 파서 구축하고 PR을 날렸더니 dev에 있는 모든 커밋들이 main으로 머지돼서 다시 main에서 브랜치 팠습니당 ... 
- 대부분의 프로젝트가 main 에서 배포한다고 해서 main에서 배포하는 걸로 설정해뒀습니다.
---
---
---
> feat : cicd  파이프라인  구축

- package-lock.json
- src/components/components.js
- src/controllers/recoms.controller.js
- src/dtos/recoms.dto.js
- src/errors.js
- src/repositories/recoms.repository.js
- src/routes/recoms.router.js
- src/services/recoms.service.js
- 추천 곡에 좋아요/별로예요 누르기 API 구현
- RequestBodyError 공통 에러 추가
---
userRecomsSong 테이블의 isLiked 값이 default(false)로 설정되어 있는데 좋아요/별로예요가 안 눌렸을 경우 null로 설정되어야 해서 default값을 빼야 할 것 같습니다. 하지만 db 수정이 복잡하므로... 2차 배포 전 한꺼번에 수정하도록 하겠습니다...! 
---
---
---
> [FEAT] 추천 곡에 좋아요/별로예요 누르기 API 구현

- package-lock.json
- package.json
- src/controllers/recoms.controller.js
- src/routes/recoms.router.js
- src/services/gemini.service.js
- src/services/recoms.service.js
- Gemini를 이용하여 추천 곡 코멘트를 작성하는 API 구현
---
- 1분에 60회, 1일에 1000회를 무료 제공하기 때문에 선택했으나, 추후 유료로 전환될 가능성 있음
---
- prompt가 null 일 때 (AI 코멘트를 작성할 때 원하는 조건이 없는 경우)
- prompt가 null이 아닐 때 (AI 코멘트를 작성할 때 원하는 조건이 있는 경우)
---
---
> [FEAT] AI를 이용하여 추천 곡 코멘트 작성하기 API 구현

- src/controllers/recoms.controller.js
- src/dtos/recoms.dto.js
- src/errors.js
- src/repositories/recoms.repository.js
- src/routes/recoms.router.js
- src/services/recoms.service.js
- src/utils/validate.js
- 답장 조회 API 구현
- service 레이어에서 공통되는 예외 처리 코드를 validate.js로 뺌
---
---
---
---
> [FEAT] 답장 조회 API 구현

- src/controllers/users.controller.js
- src/repositories/users.repository.js
- src/routes/routes.index.js
- src/routes/users.router.js
- src/services/gemini.service.js
- src/services/recoms.service.js
- src/services/users.service.js
- 유저 아이디가 중복인지 확인하는 기능 구현
---
Postman으로 테스트를 했을 때는 응답이 잘 나오는데, swagger로 테스트를 하면 계속 jwt 에러가 나옵니다.. 
2차 배포 전에 swagger 부분 검토해봐야 할 것 같아요 .. !! 
---
- 유저 아이디가 중복임 / 사용 불가
- 유저 아이디가 중복이 아님 / 사용 가능
---
- swagger 작성 인증 오류 해결 해야함
- GET일 때 request body가 있으면 오류남 ... 몰랐음 ... 까먹은거였나
---
> feat : 유저 아이디 중복 확인하기 API 구현

- index.js
- src/components/components.js
- src/controllers/recoms.controller.js
- src/controllers/users.controller.js
- src/errors.js
- src/repositories/recoms.repository.js
- src/services/recoms.service.js
- swagger 실패 응답 형식 변경
- POST API 스웨거 작성할 때 request body 작성하지 않아서 추가로 작성
---
---
응답 실패했을 때 나오는 형식입니다. 
- code = 에러코드 (상태코드 아님) 
- message = 에러 발생했을 때 나오는 에러 메세지
---
---
> [REFACTOR] Swagger 실패 응답 형식 수정

- src/components/components.js
- src/controllers/users.controller.js
- src/errors.js
- src/services/users.service.js
- 날짜 또는 시간 형식이 잘못되었을 때 에러 메세지 추가
- 이에 맞춰 스웨거 작성
---
---
- 날짜 형식 잘못됐을 경우
- 시간 형식 잘못됐을 경우
---
---
> [FIX]  날짜, 시간 형식 오류 발생했을 때 로직 추가 

- src/controllers/recoms.controller.js
- src/dtos/recoms.dto.js
- src/repositories/recoms.repository.js
- src/routes/recoms.router.js
- src/services/recoms.service.js
추천 기록 리스트(생성날짜 내림차순으로 조회) API 구현
---
스웨거는 dev에 머지하고 하겠습니다.
---
---
---
> [FEAT] : 추천 기록 리스트 조회 API 구현

- prisma/migrations/20250721133724_/migration.sql
- prisma/schema.prisma
- src/controllers/recoms.controller.js
- src/dtos/recoms.dto.js
- src/errors.js
- src/repositories/artists.repository.js
- src/repositories/recoms.repository.js
- src/services/recoms.service.js
- src/services/spotify.service.js
- iTunes API 를 이용하여 노래 불러오기
- Artist 테이블, Sing 테이블 추가
---
---
---
---
> [FIX] API 변경 및 DB 수정

- src/components/components.js
- src/controllers/users.controller.js
- src/errors.js
- src/repositories/users.repository.js
- src/services/users.service.js
- 반환값에서 referenceId 삭제
- 에러 코드 세분화 (CursorError, AuthError)
---
---
---
---
> [REFACTOR] referenceId 삭제 및 에러 코드 세분화

- package-lock.json
- package.json
- prisma/seed.js
- src/cron/scheduler.js
- src/dtos/recoms.dto.js
- src/errors.js
- src/index.js
- src/repositories/recoms.repository.js
- src/services/gemini.service.js
- src/services/recoms.service.js
- src/services/spotify.service.js
1. 매분마다 user 테이블 검사
2. isDelivered === false && recomsTime <= now()인 유저 목록을 가져옴 (오늘 노래를 수신하지 않았고, 추천 희망 시간이 현재 시간보다 이전인 유저)
3. userRecomsSong에서 sender===userId && createdAt === 오늘 날짜인 데이터 있나 검사 -> true여야 추천 곡을 받을 수 있음
4. userRecomsSong에서 receiverId===null인 추천 목록을 가져옴
4.1. 추천 목록이 있으면 목록이 소진될 때까지 receiverId 컬럼에 userId를 넣어줌
4.1.1 만약 본인이 보낸 곡을 추천 받았을 경우, 다음 추천 목록으로 넘어감. 추천 목록이 없을 경우 AI 추천으로 넘어감.
4.2. 추천 목록이 없거나 소진되었다면 AI 추천으로 넘어감
4.2.1. AI에게 아티스트 이름과 코멘트를 요청하고 iTunes에서 search url로 정보를 받아옴
-> 아티스트 이름으로 한 이유? AI에게 iTunes ID를 요청하면 없는 ID를 만들어서 주고, title을 받아오면 노래 제목이 겹칠 가능성이 많음. 따라서 인디 밴드 아티스트 이름을 검색한 후, 아티스트의 노래 중 랜덤으로 하나를 선택해서 반환. 
-> 데이터 불러오는 도중 오류가 날 경우 backup 데이터 사용 (고고학의 파도)
4.2.2 노래를 recomsSong과 userRecomsSong 테이블에 저장하고 receiverId에 userId를 넣어줌
5. user 테이블의 isDelivered(오늘 노래를 수신했는지) 컬럼을 …
> [FEAT] AI 추천 곡 생성 및 추천 곡 수신 로직 구현

- src/repositories/users.repository.js
- src/services/artists.service.js
- src/services/users.service.js
- 알림 센터, 추천 아티스트 목록 limit값을 20으로 변경
- 알림 센터 조회 API response body에서 content 필드 제거
---
---
---
---
> [REFACTOR] limit값 변경 및 response body에서 content 필드 제거

- prisma/migrations/20250801023842_/migration.sql
- prisma/schema.prisma
- src/components/components.js
- src/controllers/recoms.controller.js
- src/cron/scheduler.js
- src/errors.js
- src/services/recoms.service.js
- replies가 없을 때 답장 조회 API를 호출 시 커스텀 에러를 반환
---
---
---
---
> [FIX] 답장 조회 API 수정

- src/services/gemini.service.js
Gemini 버전 낮추기
---
Gemini 1.5 pro -> Gemini 1.5 Flash 로 변경하여 성능에 변화가 있을 수 있습니다.
---
Flash가 사용됨을 확인할 수 있습니다.
---
---
> [REFACTOR] Gemini 버전 낮추기

- src/controllers/oauth.controllers.js
- src/routes/oauth.router.js
- 로그아웃 기능 구현
---
- 로그아웃 시, accessToken과 refreshToken을 redis 캐시에서 삭제하도록 구현
---
-> accessToken, refreshToken 삭제된 것 확인 가능
---
---
> [FEAT] 로그아웃 기능 구현

- .github/workflows/deploy.yml
deploy.yml에서 docker container, image, network 삭제
---
---
---
---
> [FIX] docker container, image, network 삭제

- package-lock.json
- src/controllers/oauth.controllers.js
- src/services/musicAPI.service.js
- src/services/nodemailer.service.js
해당 파일의 몇몇 함수의 에러 응답 형식이 다른 것을 발견했습니다.
---
---
[기존]
[수정 후]
---
---
> [refactor] 에러 응답 코드 수정

- src/controllers/oauth.controllers.js
응답 에러 최종 수정했습니다.
---
---
---
---
> [REFACTOR] 응답 에러 최종 수정

- src/cron/scheduler.js
- src/services/recoms.service.js
- src/services/users.service.js
- 아티스트가 한 명일 때도 artistNames에 배열이 들어가도록 수정하여 for문에 진입할 수 있게끔 했습니다.
- 회원가입할 때 redis set에 유저 아이디를 추가하여 추천 곡을 받을 대상이 되도록 하였습니다. (로그인할 때 추가하면 당일에 두 번 이상 추천 곡을 받을 수도 있기 때문)
---
---
---
---
> [FIX] 아티스트가 한 명일 때도 배열을 반환하도록 수정

- src/controllers/users.controller.js
마이페이지 수정 API swagger request-body를 최신 버전으로 수정하였습니다.
---
---
---
---
> [FIX] 마이페이지 수정 API swagger 수정

- src/controllers/users.controller.js
마이페이지의 프로필 사진과 배경 이미지를 첨부하고, 삭제 플래그(rmPhoto, rmBackImg)를 false를 하면 안 올라가는 현상이 발생함.
false시 올라가도록 작업함.
---
---
---
---
> [FIX] 마이페이지 이미지 업로드시 삭제플래그 에러 수정

- src/services/recoms.service.js
하루 한 곡 주석 해제했습니다.
---
---
---
---
> [FIX] 하루 한 곡 주석 해제

- src/dtos/artists.dto.js
- src/repositories/artists.repository.js
아티스트 채널 조회 API에 아티스트명 추가
---
---
---
---
> [FIX] 아티스트 채널 조회 API에 아티스트명 추가

- src/repositories/recoms.repository.js
추천 기록 캘린더 내가 추천한 곡 바로 뜨게 설정
---
---
---
---
> [FIX] 추천 기록 캘린더 내가 추천한 곡 바로 뜨게 설정
